[package]
name = "game-of-life"
version = "0.1.0"
edition = "2021"

[dependencies]
tdriver = { path = "../tdriver" }

[profile.dev]
panic = "abort"
opt-level = "z"

[profile.release]
panic = "abort"
opt-level = "z"

