[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlink.x"]

[build]
target = ["riscv32i-unknown-none-elf", "x86_64-unknown-linux-gnu"]
# target = ["x86_64-unknown-linux-gnu"]
# target = ["x86_64-unknown-linux-gnu", "riscv32i-unknown-none-elf"]

[env]
EMU_TICK_RATE = "100"

[alias]
rbuild = "build --target riscv32i-unknown-none-elf --release"
xbuild = "build --target x86_64-unknown-linux-gnu"
wbuild = "build --target x86_64-pc-windows-msvc"
rb = "rbuild"
xb = "xbuild"
wb = "wbuild"

rdoc = "doc --target riscv32i-unknown-none-elf --release"
xdoc = "doc --target x86_64-unknown-linux-gnu"
wdoc = "doc --target x86_64-pc-windows-msvc"
rd = "rdoc"
xd = "xdoc"
wd = "wdoc"

