[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "llvm-args=-ffast-math"]

[build]
target = ["riscv32i-unknown-none-elf", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]

[alias]
rbuild = "build --release --target riscv32i-unknown-none-elf"
xbuild = "build --target x86_64-unknown-linux-gnu"
wbuild = "build --target x86_64-pc-windows-msvc"
rb = "rbuild"
xb = "xbuild"
wb = "wbuild"

rdoc = "doc --release --target riscv32i-unknown-none-elf"
xdoc = "doc --target x86_64-unknown-linux-gnu"
wdoc = "doc --target x86_64-pc-windows-msvc"
rd = "rdoc"
xd = "xdoc"
wd = "wdoc"

xrun = "run --target x86_64-unknown-linux-gnu"
wrun = "run --target x86_64-pc-windows-msvc"
xr = "xrun"
wr = "wrun"

rsize = "size --release --target riscv32i-unknown-none-elf"
rs = "rsize"

robjdump = "objdump --release --target riscv32i-unknown-none-elf"
rod = "robjdump"

