name: In Game Tests
run-name: In Game Tests
on: 
  push:
    paths:
    - 'computer.wld'
    - 'test/**'
    - 'tinterface/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  riscof:
    name: RISCV Compliance Tests
    runs-on: ubuntu-latest
    container: misprit7/computerraria:latest
    steps:
    - name: Compile WireHead
      run: |
        cd /root/.local/share/Terraria/tModLoader/ModSources &&\
        git clone https://github.com/misprit7/WireHead.git &&\
        cd WireHead &&\
        dotnet build

    - name: Checkout computerraria
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install tinterface
      run: pip3 install -e ./tinterface

    - name: Run riscof tests
      run: ./run-tests.sh

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Result summary
        path: |
          ./test/riscof_work/

