name: Rust Apps
run-name: Rust Apps
on: 
  push:
    paths:
      - 'app/**'
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout computerraria
      uses: actions/checkout@v3

    - name: Build
      run: |
        for i in app/* ; do
          if [ -d "$i" ]; then
            echo "Building $i" &&
            cargo build --verbose --manifest-path="$i/Cargo.toml"
            cargo rbuild --verbose --manifest-path="$i/Cargo.toml"
          fi
        done


