name: Tests
run-name: Continuous integration tests
on: [push]
jobs:
  riscof:
    name: RISCV compliance tests
    runs-on: ubuntu-latest
    container: misprit7/computerraria:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install tinterface
        run: pip3 install -e ./tinterface

      - name: Run riscof tests
        run: ./run-tests.sh

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Result summary
          path: ./test/riscof_work/report.html

